services:
  app:
    build:
      dockerfile: containers/app/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    entrypoint: ["sh", "-c"]
    command: ["npx prisma generate && npx prisma migrate deploy && npm run dev"]

  ws-server:
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ["node", "--watch"]
    command: ["ws-server.js"]
