# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    deployment-app.yaml                              :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahamuyel <ahamuyel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/27 18:28:20 by ahamuyel          #+#    #+#              #
#    Updated: 2026/04/27 18:28:21 by ahamuyel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cur10usx-app
  labels:
    app: cur10usx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cur10usx-app
  template:
    metadata:
      labels:
        app: cur10usx-app
    spec:
      containers:
        - name: app
          image: albertoih/cur10usx-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_URL
              value: "http://cur10usx-api-service:4200"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi" # Next.js costuma precisar de um pouco mais que 128Mi
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: / 
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10