apiVersion: v1
kind: Service 
metadata:
  name: cur10usx-web-service
  labels:
    app: cur10usx-web-service
spec:
  selector:
    app: cur10usx-web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort