# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    service-app.yaml                                   :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ahamuyel <ahamuyel@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/27 18:28:26 by ahamuyel          #+#    #+#              #
#    Updated: 2026/04/28 17:14:50 by ahamuyel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service 
metadata:
  name: cur10usx-app-service
  labels:
    app: cur10usx-app-service
spec:
  selector:
    app: cur10usx-app
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort