apiVersion: v1
kind: Service 
metadata:
  name: cur10usx-api-service
  labels:
    app: cur10usx-api-service
spec:
  selector:
    app: cur10usx-api-service
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP