port 6379
bind 0.0.0.0
protected-mode yes
databases 16

save 900 1
save 300 10
save 60 10000

maxmemory 256mb
maxmemory-policy allkeys-lru

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

loglevel notice
logfile ""

client-output-buffer-limit normal 0 0 0
client-output-buffer-limit pubsub 32mb 8mb 60
